Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -7,4 +7,6 @@ jobs:
      - uses: actions/checkout@v3
      - name: run a sample sample github action
        run: echo "this workflow run successfully for this particular action"
+     - name: imulating an error
+       run: echo "error taking place";exit 1
    
